const List<Map<String, dynamic>> enStateCode = [
  {'text': 'Jammu Kashmir (1)', 'id': 1},
  {'text': 'Himachal Pradesh (2)', 'id': 2},
  {'text': 'Punjab (3)', 'id': 3},
  {'text': 'Chandigarh (4)', 'id': 4},
  {'text': 'Uttarakhand (5)', 'id': 5},
  {'text': 'Haryana (6)', 'id': 6},
  {'text': 'Delhi (7)', 'id': 7},
  {'text': 'Rajasthan (8)', 'id': 8},
  {'text': 'Uttar Pradesh (9)', 'id': 9},
  {'text': 'Bihar (10)', 'id': 10},
  {'text': 'Sikkim (11)', 'id': 11},
  {'text': 'Arunachal Pradesh (12)', 'id': 12},
  {'text': 'Nagaland (13)', 'id': 13},
  {'text': 'Manipur (14)', 'id': 14},
  {'text': 'Mizoram (15)', 'id': 15},
  {'text': 'Tripura (16)', 'id': 16},
  {'text': 'Meghalaya (17)', 'id': 17},
  {'text': 'Assam (18)', 'id': 18},
  {'text': 'West Bengal (19)', 'id': 19},
  {'text': 'Jharkhand (20)', 'id': 20},
  {'text': 'Orissa (21)', 'id': 21},
  {'text': 'Chhattisgarh (22)', 'id': 22},
  {'text': 'Madhya Pradesh (23)', 'id': 23},
  {'text': 'Gujarat (24)', 'id': 24},
  {'text': 'Daman And Diu (25)', 'id': 25},
  {'text': 'Dadra And Nagar Haveli (26)', 'id': 26},
  {'text': 'Maharashtra (27)', 'id': 27},
  {'text': 'Andhra Pradesh Old (28)', 'id': 28},
  {'text': 'Karnataka (29)', 'id': 29},
  {'text': 'Goa (30)', 'id': 30},
  {'text': 'Lakshadweep (31)', 'id': 31},
  {'text': 'Kerala (32)', 'id': 32},
  {'text': 'Tamil Nadu (33)', 'id': 33},
  {'text': 'Puducherry (34)', 'id': 34},
  {'text': 'Andaman And Nicobar Islands (35)', 'id': 35},
  {'text': 'Telangana (36)', 'id': 36},
  {'text': 'Andhra Pradesh New (37)', 'id': 37},
];

const List<Map<String, dynamic>> EnProductType = [
  {'name': 'Goods', 'id': 1},
  {'name': 'Service', 'id': 2}
];

List<Map<String, dynamic>> enInvTypeForDropdown = [
  {'text': 'Sales Invoice', 'id': 1},
  {'text': 'Cash Invoice', 'id': 2},
  {'text': 'Sale Return', 'id': 3},
  {'text': 'Sales Quotation', 'id': 4},
  {'text': 'Sales Order', 'id': 5},
  {'text': 'Performa Invoice', 'id': 6},
  {'text': 'Sales Chalan', 'id': 7},
  {'text': 'Purchase Order', 'id': 8},
  {'text': 'Purchase Invoice', 'id': 9},
  {'text': 'Purchase Return', 'id': 10},
  {'text': 'Purchase Quotation', 'id': 11},
  {'text': 'Opening Stock', 'id': 12},
  {'text': 'Transfered In Stock', 'id': 13},
  {'text': 'Transfered Out Stock', 'id': 14},
  {'text': 'Adjusted Stock', 'id': 15},
  {'text': 'Purchase Challan', 'id': 16},
  {'text': 'Payment Voucher', 'id': 17},
  {'text': 'Receipt Voucher', 'id': 18},
  {'text': 'Journal Voucher', 'id': 19},
  {'text': 'Contra Voucher', 'id': 20},
  {'text': 'Absolute Stock', 'id': 21},
  {'text': 'Sales Enquiry', 'id': 23},
  {'text': 'Payment Open Brc', 'id': 24},
  {'text': 'Receipt Open Brc', 'id': 25},
  {'text': 'Costing', 'id': 26},
  {'text': 'Material Slip', 'id': 27},
  {'text': 'Material In', 'id': 28},
  {'text': 'Material Out', 'id': 29},
  {'text': 'Sales Challan Return', 'id': 30},
  {'text': 'Purchase Challan Return', 'id': 31},
];
